### ISSUE TITLE
Crashes in Production

### ISSUE THREAD

**Issue by tomLadder** [iamolegga/react-native-launch-arguments#2]
Thanks for this library. We logged some user crashes of our production app due to this lib.

```
com.facebook.react.common.JavascriptException: Error: Exception in HostObject::get(propName:LaunchArguments): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.app.Activity.getIntent()' on a null object reference
```

**Comment by iamolegga** [comment]
thanks for report. Looks like one extra check for this is required. Ok I'll try to fix this soon

**Comment by tomLadder** [comment]
@iamolegga Thank you for the fast respond.  The Error occures mostly in background sate (which makes sense). An extra check for `getCurrentActivity().getIntent()` in `LaunchArgumentsModule.java ` should do the job :)

![image](https://user-images.githubusercontent.com/20393156/96430176-21215800-1202-11eb-8039-abcc5c920d0e.png)

**Comment by iamolegga** [comment]
@tomLadder please check v1.0.1

**Comment by tomLadder** [comment]
@iamolegga Looks good now. Thanks for the quick fix 🏎
