### ISSUE TITLE
3.0.0 has no dist folder deployed

### ISSUE THREAD

**Issue by kyle-ssg** [iamolegga/react-native-launch-arguments#26]
![image](https://user-images.githubusercontent.com/8608314/153719200-1945cbf8-5d25-4a4d-a442-b130f91e7f4b.png)

**Comment by iamolegga** [comment]
Sorry, should add the ci finally for this. Let's merge #25 and I'll publish a new version

**Comment by iamolegga** [comment]
fixed in `3.0.1`
