### ISSUE TITLE
npm package v1.0.1 missing dist

### ISSUE THREAD

**Issue by tomLadder** [iamolegga/react-native-launch-arguments#4]
Error: While trying to resolve module `react-native-launch-arguments` from file `/Users/someuser/repos/xyz/xyz/src/context/GlobalContext.tsx`, the package `/Users/someuser/repos/xyz/Numerology/xyz/react-native-launch-arguments/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/someuser/repos/xyz/xyz/node_modules/react-native-launch-arguments/dist/index.js`. Indeed, none of these files exist:

**Comment by iamolegga** [comment]
🤦‍♂️sorry, just published 1.0.2, check it out please 🙂

**Comment by tomLadder** [comment]
Works now. Thanks @iamolegga
