### ISSUE TITLE
Empty set of launch arguments if used in a very early stage (Android)

### ISSUE THREAD

**Issue by d4vidi** [iamolegga/react-native-launch-arguments#44]
Hi, Detox maintainer here 👋🏻
I've recently been making usage of this library (great job, BTW!) in Detox's self-test project. We see that quite clearly, on Android at least, if the launch arguments are used in a very early stage (e.g. in the app's `index.js`), then intermittently, an empty arguments object is returned.

For example:
```js
import React, {Component} from 'react';
import {
  AppRegistry,
} from 'react-native';
import { LaunchArguments } from 'react-native-launch-arguments';

console.warn('DEBUG', LaunchArguments.value());

export default class ExampleApp extends Component {
// ...
}

AppRegistry.registerComponent('example', () => ExampleApp);

```

If the app is repeatedly launched using `device.launchApp({ launchArgs: { 'my': 'arg' } })`, then you would see logs looking somewhere along the lines of:

```
DEBUG { my: arg }
DEBUG { my: arg }
DEBUG {}
DEBUG { my: arg }
DEBUG { my: arg }
DEBUG { my: arg }
DEBUG {}
```

Side note: I suppose there's a race condition here, sorting out the arguments into the NativeModule's constants.

**Comment by d4vidi** [comment]
@iamolegga do you think there's a way to get this sorted out somehow? Perhaps [Detox's implementation](https://github.com/wix/Detox/blob/master/detox/test/android/app/src/main/java/com/example/NativeModule.java#L82) could provide a decent alternative, although asynchronous.

**Comment by iamolegga** [comment]
@d4vidi sorry, I'm not able to investigate this in the nearest future. But I would be glad to merge fix for this. Maybe in the late 2022 I'll get back to this issue (and all the others) if on my current project we will use this lib

**Comment by d4vidi** [comment]
I could provide a fix but best if you give a general approval 😄

**Comment by iamolegga** [comment]
PR's are always welcome 🙂

**Comment by d4vidi** [comment]
>Perhaps [Detox's implementation](https://github.com/wix/Detox/blob/master/detox/test/android/app/src/main/java/com/example/NativeModule.java#L82) could provide a decent alternative, although asynchronous.

I meant, an approval of this, in particular.

**Comment by iamolegga** [comment]
So you want to replace built-in method with the detox's one? Then we need to check that:

- [ ] returned data is consistent between platforms
- [ ] what about appium? maybe detect somehow which framework is installed and then chose the right method to resolve data.

Does [getLaunchArguments](https://github.com/wix/Detox/blob/master/detox/test/android/app/src/main/java/com/example/NativeModule.java#L82) mentioned in the detox's docs? If this is available for the end user then this library can be deprecated in favor of detox built-in method, right?

**Comment by d4vidi** [comment]
It is not a Detox top-level API - Detox never runs inside the app. The Detox code I pointed at was of Detox's self-test app.

**Comment by d4vidi** [comment]
The main question is whether you'd be willing to change the API in a breaking way, namely from:
```js
import {LaunchArguments} from 'react-native-launch-arguments';
const args = LaunchArguments.values()
```
to something along the lines of:

```js
import {  NativeModules } from 'react-native';
const { LaunchArguments } = NativeModules;
const args = await LaunchArguments.values();
```

**Comment by iamolegga** [comment]
I believe we can do this inside index.js of this module:

```ts
import {  NativeModules } from 'react-native';
const { LaunchArguments } = NativeModules;
export { LaunchArguments }
```

then only asynchrony will changed, and from my point of view that's ok if the bug can be fixed only this way

**Comment by d4vidi** [comment]
Cool

**Comment by richardruiter** [comment]
> I believe we can do this inside index.js of this module:
> 
> ```ts
> import {  NativeModules } from 'react-native';
> const { LaunchArguments } = NativeModules;
> export { LaunchArguments }
> ```
> 
> then only asynchrony will changed, and from my point of view that's ok if the bug can be fixed only this way

Is this fixed?

**Comment by PinhoL** [comment]
Been happening to me as well, Android only

**Comment by d4vidi** [comment]
Now trying to actively get this fixed

**Comment by d4vidi** [comment]
Still researching. This is what I've done so far: https://github.com/wix/Detox/pull/4060

**Comment by d4vidi** [comment]
Here are the full details: https://github.com/facebook/react-native/issues/37518

**Comment by iamolegga** [comment]
Should be fixed in #72 by @d4vidi

Please try `npm i react-native-launch-arguments@next` and comment here if it works correctly, I'll publish it as a new major release then.

**Comment by d4vidi** [comment]
> Should be fixed in #72 by @d4vidi
> 
> Please try `npm i react-native-launch-arguments@next` and comment here if it works correctly, I'll publish it as a new major release then.

Great, thank you. I'll integrate that back into the Detox self-test app, we'll see how it goes.

**Comment by d4vidi** [comment]
Seems like the problem hasn't been resolved, according to Detox: There is a still another subtle update required: #73.

**Comment by iamolegga** [comment]
@d4vidi I've just published [4.0.0-rc.1](https://www.npmjs.com/package/react-native-launch-arguments/v/4.0.0-rc.1). Please try again `npm i react-native-launch-arguments@next`

**Comment by d4vidi** [comment]
Thanks!

**Comment by d4vidi** [comment]
@iamolegga things are looking stable on the Detox side (https://github.com/wix/Detox/pull/4060) 👍🏻

**Comment by iamolegga** [comment]
@d4vidi done ✅
