### ISSUE TITLE
[question] Passing process parameters from ADB / Appium

### ISSUE THREAD

**Issue by bgalamb** [iamolegga/react-native-launch-arguments#5]
Hi !
I am trying to use the RN module to get the launch arguments in my RN project. iOS is working fine but I am running into trouble with Android. There is something which is not clear from the readme...regarding how exactly the parameters are passed.

The following command is executed when I start the app on emulator when I want to run tests (with [Appium](http://appium.io/docs/en/writing-running-appium/caps/))

`adb -P 5037 -s emulator-5554 shell am start -W -n com.reaxx/com.reaxx.MainActivity -S --es launchArgs '"-serverURL myserver"''`

Unfortunately its not working and I wonder if this **is right way to pass the parameters to the module**?  

(I don't know what is the exact command that detox executes when starts the app...)

It looks like the intent [arguments](https://developer.android.com/studio/command-line/adb#IntentSpec) which are passed like this should be read with [Intent.getStringExtra()](https://developer.android.com/reference/android/content/Intent.html#getStringExtra(java.lang.String)) and not   [Intent.getBundleExtra() ](https://developer.android.com/reference/android/content/Intent#getBundleExtra(java.lang.String))

If this is the case, can you add support for ADB / Appium? It would broaden audience...

Br

**Comment by iamolegga** [comment]
Hi, unfortunately I didn't work with appium, but prs are always welcome if anyone can help with this

**Comment by bgalamb** [comment]
Hi. I created a minimal modification which can help people using Appium.
PR https://github.com/iamolegga/react-native-launch-arguments/pull/6 Pls. check.
